### ISSUE TITLE
The node feature discovery operator fails to create pods in 4.15 clusters

### ISSUE THREAD

**Issue by David-M-IBM** [IBM/cloud-pak-deployer#754]
**Describe the bug**
I think this bug is documented and explained in [this issue](https://issues.redhat.com/browse/OCPBUGS-30918) and I think that it can be resolved by changing [this file/line](https://github.com/IBM/cloud-pak-deployer/blob/8a4c83b3ab2f9814aa54110c7e4b143e21d6ea7d/automation-roles/40-configure-infra/nfd-operator/templates/nfd-cr.j2#L11) to instead be image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v{{ _p_current_ocp_version }} when the version is 4.15. Updating the value manually in the nodes resolved the issue.

**To Reproduce**
1. make openshift:gpu:install: true when running the cloud pak deployer in a 4.15 cluster
2. It will pass the steps but will error when creating pods with this error - Error: initializing source docker://registry.redhat.io/openshift4/ose-node-feature-discovery:v4.15: reading manifest v4.15 in registry.redhat.io/openshift4/ose-node-feature-discovery: manifest unknown

**Screenshots**
![image (1)](https://github.com/user-attachments/assets/097ae612-a57e-4d88-9653-82c8b6749e28)
![image (2)](https://github.com/user-attachments/assets/e6d6df6e-a2d7-462a-99dc-3254cf462cf7)

**Comment by fketelaars** [comment]
Thanks for notifying us @David-M-IBM . For now I'm changing to the rhel9 image only for OpenShift 4.15 (despite what the documentation says): https://docs.openshift.com/container-platform/4.15/hardware_enablement/psap-node-feature-discovery-operator.html#creating-nfd-cr-cli-disconnected_psap-node-feature-discovery-operator

Do you think the rhel9 suffix will be required for future releases of OpenShift as well?

**Comment by fketelaars** [comment]
Fixed in branch `openshift-415-patches`. Once tested I will merge with `main` as a hotfix.

**Comment by fketelaars** [comment]
Item fixed for OpenShift 4.15, merged with `main` branch

**Comment by David-M-IBM** [comment]
This looks like it's still present in the 4.16 OpenShift as well and the logic should be changed to make it `registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v{{ _p_current_ocp_version }}` for all versions after 4.14.

![image](https://github.com/user-attachments/assets/0028d7cd-1981-43d5-970e-2172c3ecbec9)

I tried changing it to add -rhel9 and it worked in 4.16.

**Comment by fketelaars** [comment]
I see you self-assigned. If you can make the change, I will review and merge.

**Comment by David-M-IBM** [comment]
Nice, kk I was thinking of just changing the comparison to compare floats like this:

> {% if _p_current_ocp_version|float() >= 4.15 %}
>     image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v{{ _p_current_ocp_version }}
> {% else %}
>     image: registry.redhat.io/openshift4/ose-node-feature-discovery:v{{ _p_current_ocp_version }}
> {% endif %}

But I need to get a 4.16, 4.15, and 4.14 cluster to test.
